version: "3.9"

services:

  kafka:
    image: bitnami/kafka:3.7
    container_name: mars-kafka-dev
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
<<<<<<< HEAD
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
=======
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
>>>>>>> origin/network
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    healthcheck:
<<<<<<< HEAD
      test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
=======
      test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
>>>>>>> origin/network
      interval: 10s
      timeout: 10s
      retries: 15

  simulator:
    image: mars-iot-simulator:multiarch_v1
    ports:
      - "8080:8080"
    healthcheck:
<<<<<<< HEAD
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
=======
      test: ["CMD", "curl", "-f", "http://simulator:8080/health"]
>>>>>>> origin/network
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on: [kafka]
